Fix `IllegalStateException` in native mode when JSON-serializing Proto classes
```
java.lang.IllegalStateException: Generated message class "com.google.protobuf.DescriptorProtos$FeatureSet" missing method "getFieldPresence"
```

Signed-off-by: nscuro <nscuro@protonmail.com>