Fix `NoClassDefFoundError` due to outdated Kafka clients version
Quarkus has updated Kafka clients to 3.7.0, but we overwrite the version to 3.6.1, causing `java.lang.NoClassDefFoundError: org/apache/kafka/streams/state/BuiltInDslStoreSuppliers$RocksDBDslStoreSuppliers`.

Note, kafka-clients is explicitly kept at 3.6.1 for notification-publisher, as Confluent Parallel Consumer is not yet compatible with the newer 3.7.0 version.

Signed-off-by: nscuro <nscuro@protonmail.com>